- ublue-updater.spec
Changes permissions from 0644 to 0755 on all update scripts
> fix: Make update scripts executable in spec file

- update-ublue
I made a few small changes to apply some more pythonic approaches to things.
* One common pattern is to define the log handler once at the top of the file, keeps the code more DRY
* Comments typically follow the same indent as code
* When you have an uncertain list of things to print you can use `.join` to merge lists into a string at the end
* I'm not sure about `exit` it's not a Python built-in and I think it was working purely because you were getting an exception that exit wasn't defined. I moved it to an Exception which will trigger the exit code of 1 automatically in Python
> fix: apply some small python cleanups

- files/usr/lib/systemd/user/ublue-update.service
- files/usr/lib/systemd/user/ublue-update.timer
ublue-update can inform systemd that it failed for a number of reasons including checks not passing or an update simply not being available at that time. Currently the service is bugged in that if a check fails, it will run again 15 minutes later, adding additional complications. This defeats the point of having checks to begin with as it introduces added overhead. Additionally, when an update actually is available, we can now allow the user to override the checks and update anyway, making this something that actually gets in the way. If consecutive update checks fail, the user may be constantly bombarded with notifications saying that an update is available, even if one isn't
This commit addresses the situation. Updates will now run 15 minutes after boot instead of one hour later, …
> fix: Adjust update service and timer

- .gitignore
- pyproject.toml
- src/ublue_update/cli.py
- src/ublue_update/notification_manager.py
- ublue-update.spec.rpkg
- Removed all dependency on the deprecated notify2 library
- Added the notification_manager module
Things to consider:
- abstract all dbus and glib logic to notification_manager (initializing the bus, setting up main loop, etc)
- Add notification object? The idea would be to make adding actions easier and not force every notification to use the same actions, dunno how much this would complicate things
> feat: remove dependency on notify2 and replace with simple in-house module

- Containerfile.builder
- src/ublue_update/cli.py
- src/ublue_update/notification_manager.py
This makes it so it only has an exit code of one when it doesn't ask the user for updates. If the user is prompted to accept an update and accepts, the program will exit with OK, otherwise it will throw the exception
> fix: fix program exiting telling user checks have failed when running from notification

- src/ublue_update/update_checks/system.py
In some cases, the url may already contain the protocol. In such cases, we need to verify it's already there otherwise it is duplicated
> fix: Check if the url already contains the protocol during update checks

- src/ublue_update/update_checks/system.py
This simplifies the retrieval of the URL we pass to Skopeo by just dropping the registry and retaining the rest of the URL
> fix: Just drop the registry reference in URL for latest image

- src/ublue_update/cli.py
- src/ublue_update/update_checks/wait.py
Prevents updates from being triggered while an existing transaction exists
Thanks to @akdev1l for help with the implementation :)
> feat: Add module that waits for transaction completion before updating

- src/ublue_update/cli.py
This fixes dbus notifications, after accidentally breaking them in the previous PR
> fix: remove typo in arguments for notify-send

- .github/workflows/build.yml
This will make use of wip akdev1l/copr-build (I will fork this into ublue-os/copr-build when it is ready) to generate copr repo pointing to this github repo.
The copr repo build will be triggered by this action as well.
I have removed the scheduled 5 AM build because the application build does not really change that often (the dependencies get pulled in when RPM is installed so it will not install outdated dependencies)
> chore: add copr build so we are packaged in COPR

- files/etc/ublue-update.d/system/00-system-update.sh
this should hopefully rectify the rebasing woes. Just need to test it, hopefully this should remove the blockers needed to integrate with bluefin
> fix: preserve unsigned image tag upon rebase

- rpkg.macros
To be sure the latest build version is higher then all before, we can rule out if the package manager is picking an old version based on the version tag.
Can be merged when #84  is succesfully merged into main.
> chore: bump version

- rpkg.macros
- src/ublue_update/cli.py
- src/ublue_update/update_checks/system.py
Fixes #86 
This will always return True when we are on a offline installation which contains the oci variant `oci:/var/ublue-os/image`
Add another condition to verify we want to have a dbus notification
```
Traceback (most recent call last):
File "/usr/bin/ublue-update", line 8, in <module>
sys.exit(main())
^^^^^^
File "/usr/lib/python3.11/site-packages/ublue_update/cli.py", line 255, in main
run_updates(cli_args.system, system_update_available)
File "/usr/lib/python3.11/site-packages/ublue_update/cli.py", line 177, in run_updates
if "universal-blue-update-reboot" in out.stdout.decode("utf-8"):
^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'stdout'
```
Bump the spec version with x.x.1
> fix: offline iso update

- files/etc/ublue-update.d/system/00-system-update.py
- rpkg.macros
This PR contains changes to be more carefull when to actually rebase. It won't rebase forks or images if the image-info.json is not updated to match the fork. It does rebase installations when the offline ISO is used, or upstream installations with matching image-info.json.
Fork of bluefin-dx, without updating meta information in image-info.json:
```
cat /usr/share/ublue-os/image-info.json 
{
"image-name": "bluefin-dx",
"image-flavor": "main",
"image-vendor": "ublue-os",
"image-ref": "ostree-image-signed:docker://ghcr.io/ublue-os/bluefin-dx",
"image-tag":"latest",
"base-image-name": "",
"fedora-version": "38"
}
```
```
rpm-ostree status
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
Deployments:
● …
```
> fix: be more carefull when to rebase

- src/ublue_update/update_inhibitors/hardware.py
Until giampaolo/psutil#2305 is merged, machines with no battery can fail the check if they have external devices that are reporting battery levels (#79).
In my case, my wireless Logitech headphones report 0% battery if the dongle is plugged in but the headphones are off, and even setting `min_battery_percent = 0` in the config doesn't work, because 0 is not greater than 0.
This little tweak just makes it so 0 values pass the check correctly.
Could make a special case for `min_battery_percent = 0` to skip the check entirely instead, not sure which would be more preferred.
> fix: min_battery_percent = 0 now works to "skip" battery check

- files/etc/ublue-update.d/system/00-system-update.py
- setup.cfg
When a branch file (/etc/ublue-update/branch) exists, read the chosen branch from the file and perform a rebase.
Especially useful paired with Steam's branch selection via the Steam Deck UI in Bazzite. Could also be used in other projects to switch between branches being used for development on the fly.
> feat(system-update): Allow switching between branches via rebase

- rpkg.macros
New commits are merged but the version wasn't bumped. Version currently being installed is `ublue-update-1.1.2+427912c-1.fc38.noarch` which is a 13 day old build instead of the new one with merged changes.
- https://github.com/ublue-os/ublue-update/pull/89
- https://github.com/ublue-os/ublue-update/pull/91
@EyeCantCU
> chore: version bump

- files/etc/ublue-update.d/system/00-system-update.py
- files/etc/ublue-update.d/system/01-flatpak-system-update.sh
- files/etc/ublue-update.d/system/02-flatpak-system-repair-cleanup.sh
- files/etc/ublue-update.d/user/00-flatpak-user-update.sh
- files/etc/ublue-update.d/user/01-flatpak-user-repair-cleanup.sh
- files/etc/ublue-update.d/user/02-distrobox-user-update.sh
- files/etc/ublue-update.d/user/03-fleek-user-update.sh
- files/etc/ublue-update.d/user/04-brew-update.sh
- files/usr/etc/ublue-update/topgrade-system.toml
- files/usr/etc/ublue-update/topgrade-user.toml
- files/usr/etc/ublue-update/ublue-update.toml
- rpkg.macros
- src/ublue_update/cli.py
- ublue-update.spec
This replaces the previous update mechanism entirely with [topgrade](https://github.com/topgrade-rs/topgrade).
Note that there will need to be a 2nd PR to remove the rebase code and further simplify things once the work on the new ISO is done.
Invalidates https://github.com/ublue-os/ublue-update/pull/100
> feat: Add topgrade support

- README.md
- files/usr/etc/ublue-update/ublue-update.toml
- src/ublue_update/cli.py
- src/ublue_update/config.py
- src/ublue_update/update_inhibitors/custom.py
- src/ublue_update/update_inhibitors/hardware.py
This pull request contains four small-ish fixes/improvements:
* Improve the documentation clarity in the main README.md
* Allow specifying lowercase log levels via `UBLUE_LOG` to match the behavior of most other tools
* Cleanup the config file loading logic, and avoid crashes when not all config options are specified.
* Add a `--config` CLI option to allow alternate config files when testing
...as well as two new features related to the update precondition checks (these two were the main driver for this pull request):
* Add a `network_not_metered` check to prevent downloading multiple GB of data when on metered/mobile connections
(the latter of which happened to me while using my smartphone as a hotspot).
This check should probably be enabled in all environments where NetworkManager is …
> Add network_not_metered and custom check scripts

- .github/workflows/unit.yml
- tests/unit/test_cli.py
- tests/unit/test_config.py
- tests/unit/test_filelock.py
- tests/unit/test_session.py
- tests/unit/update_checks/test_system.py
- tests/unit/update_checks/test_wait.py
- tests/unit/update_inhibitors/test_custom.py
- tests/unit/update_inhibitors/test_hardware.py
This PR contains the following changes:
- Add pytest-based unit tests
- Add Github Actions CI for unit tests
Closes #72
> Add unit tests and CI

- src/ublue_update/cli.py
- tests/unit/test_cli.py
This commit removes the "System passed checks, updating ..." which is confusing as it will trigger every 6 hours even if there is no update available to install.
If there are other opinions on how to solve this, please let me know and I am happy to code something up.
I was just very confused the last days that my system "seemed" to update, but there were no system updates available.
Maybe there could be something done with the wording.
> fix: Remove confusing Notification regarding System updates

- .gitignore
- src/ublue_update/cli.py
- src/ublue_update/session.py
- tests/unit/test_cli.py
- tests/unit/test_session.py
This PR switches from using `sudo` to handle multi-user to using `systemd-run`, allowing us to have a much easier time diagnosing problems, and not have to hack in environment variables. This PR also includes a fix for the issue: https://github.com/ublue-os/ublue-update/issues/113 where topgrade prompts for breaking changes
> feat: use systemd-run, fix topgrade

- src/ublue_update/cli.py
- src/ublue_update/session.py
- tests/unit/test_cli.py
- tests/unit/test_session.py
- ublue-update.spec
This PR supersedes: https://github.com/ublue-os/ublue-update/pull/133
`session.py` now uses the dbus API instead of using loginctl subprocess, instead using busctl as a subprocess, this can however be migrated to dbus-python easily. The dbus API is also hopefully more stable than the loginctl CLI, though we are still using busctl.
This also fixes an issue with update confirmation, where output wasn't probably being piped back into stdout when using `systemd-run`, meaning that update confirmations were impossible and `ublue-update` would error instead of update when confirming
> fix: use login1 dbus API, fix systemd-run
